#!/usr/bin/env node
// Build and check the career levels (js/levels.js):
//   1. Cook every level's par recipe on several seeds and write the mean perceived taste to js/level-targets.js.
//      It also records how each judge on the tier's panel scores the par (their own taste), which is what
//      "better than par" means for flourishes.
//   2. Score the par, each listed mistake and each flourish against those targets (0–10, SPEC §17).
//      Par must pass with the Good Soup badge on every seed; every mistake must fall short of the badge
//      and score below par. The run fails otherwise.
//
//   node tools/build-levels.js [level-id-prefix] [--seeds=3] [--check]   (--check: don't rewrite targets)
'use strict';
const fs = require('fs'), path = require('path');
const K = require('./kitchen');

const args = process.argv.slice(2);
const opt = (k, d) => { const a = args.find((s) => s.startsWith('--' + k)); return a ? (a.includes('=') ? a.split('=')[1] : true) : d; };
const only = args.find((a) => !a.startsWith('--'));
const SEEDS = +opt('seeds', 3), CHECK = opt('check', false);
const TARGETS = path.join(K.ROOT, 'js', 'level-targets.js');
const AXES = ['salty', 'sweet', 'sour', 'bitter', 'umami', 'rich', 'heat', 'aroma', 'body'];

const { LEVELS } = K.makeGame(1);
const levels = LEVELS.filter((l) => !only || l.id.startsWith(only));
const variant = (l, m) => K.resolve({ ...m, id: l.id + ':' + m.name, name: m.name, steps: m.steps || l.par });
const seeds = (spec) => Array.from({ length: SEEDS }, (_, s) => ({ spec, seed: s + 1 }));
const stars = (n) => '★'.repeat(n) + '☆'.repeat(3 - n);

(async () => {
  // 1. Targets from the par recipes.
  if (!CHECK) {
    const jobs = levels.flatMap((l) => seeds({ id: l.id, name: l.title, steps: l.par, level: l.id }));
    const res = await K.cookAll(jobs);
    const old = fs.existsSync(TARGETS) ? new Function(fs.readFileSync(TARGETS, 'utf8') + ';return LEVEL_TARGETS;')() : {};
    levels.forEach((l, n) => {
      const rs = res.slice(n * SEEDS, (n + 1) * SEEDS);
      const bad = rs.find((r) => r.error);
      if (bad) { console.log(`ERROR cooking ${l.id} par\n${bad.error}`); process.exit(1); }
      const taste = {};
      for (const ax of AXES) taste[ax] = +(rs.reduce((s, r) => s + (r.taste[ax] || 0), 0) / rs.length).toFixed(3);
      const judges = {};
      for (const j of rs[0].judges) judges[j.id] = +(rs.reduce((s, r) => s + r.judges.find((x) => x.id === j.id).taste, 0) / rs.length).toFixed(2);
      old[l.id] = { taste, judges, type: rs[0].type };
    });
    fs.writeFileSync(TARGETS, '// Generated by tools/build-levels.js from each level\'s par recipe. Do not edit by hand.\n' +
      'const LEVEL_TARGETS = ' + JSON.stringify(old, null, 1).replace(/\n\s*/g, ' ') + ';\n');
    console.log(`Wrote targets for ${levels.length} levels to js/level-targets.js\n`);
  }

  // 2. Score par, mistakes and flourishes (fresh workers load the new targets).
  const runs = [];
  for (const l of levels) {
    runs.push({ l, kind: 'par', name: 'PAR', spec: { id: l.id, name: 'par', steps: l.par, level: l.id } });
    for (const m of l.mistakes || []) runs.push({ l, kind: 'mistake', name: m.name, spec: { ...variant(l, m), level: l.id } });
    for (const f of l.flourishes || []) runs.push({ l, kind: 'flourish', name: '+ ' + f.name, spec: { ...variant(l, f), level: l.id } });
  }
  const res = await K.cookAll(runs.flatMap((r) => seeds(r.spec)));
  let problems = 0, lastTier = -1;
  const parMean = {};
  runs.forEach((run, n) => {
    const rs = res.slice(n * SEEDS, (n + 1) * SEEDS);
    const bad = rs.find((r) => r.error);
    if (bad) { console.log(`ERROR ${run.l.id} / ${run.name}\n${bad.error}`); problems++; return; }
    const L = rs.map((r) => r.level), totals = L.map((x) => x.total);
    const mean = totals.reduce((a, b) => a + b, 0) / totals.length, lo = Math.min(...totals), hi = Math.max(...totals);
    let ok = true;
    if (run.kind === 'par') { parMean[run.l.id] = mean; ok = L.every((x) => x.passed && x.badge); }
    if (run.kind === 'mistake') ok = hi < 8 && mean <= parMean[run.l.id] - 0.5;
    if (!ok) problems++;
    if (run.kind === 'par' && run.l.tier !== lastTier) { lastTier = run.l.tier; console.log(`\n=== Tier ${run.l.tier}: ${rs[0].judges.map((j) => j.judge).join(', ')} ===`); }
    if (run.kind === 'par') console.log(`\n${run.l.title}  (teaches ${run.l.teaches})`);
    const badge = (x) => (x.badge === 'perfect' ? 'PERFECT' : x.badge === 'good' ? 'GOOD' : x.passed ? 'pass' : 'CHOP');
    const per = rs[0].judges.map((j) => `${j.judge.split(' ')[0]} ${j.score}${j.handshake ? '🤝' : ''}`).join(' ');
    console.log(`  ${ok ? ' ' : '✗'} ${run.name.padEnd(20)} ${mean.toFixed(1).padStart(4)}${hi - lo > 0.05 ? ` (${lo.toFixed(1)}–${hi.toFixed(1)})` : '          '}  ${badge(L[0]).padEnd(7)} match ${L[0].match.toFixed(2)} recipe ${L[0].recipe.toFixed(2)}  [${per}]`);
    if (run.kind !== 'par' || !ok) { const notes = L[0].notes.slice(0, 2); if (notes.length) console.log(`      ${notes.join(' ')}`); }
  });
  console.log(problems ? `\n${problems} problem(s): par must pass with the Good Soup badge on every seed; mistakes must miss the badge and score below par.`
                       : '\nEvery par earns the Good Soup badge, and every mistake falls short.');
  process.exit(problems ? 1 : 0);
})();
