#!/usr/bin/env node
// Build and check the career levels (js/levels.js):
//   1. Cook every level's par recipe on several seeds and write the mean perceived taste to js/level-targets.js.
//   2. Score the par and each listed mistake against those targets. Par should earn 3 stars and every
//      mistake fewer; the run fails otherwise.
//
//   node tools/build-levels.js [level-id-prefix] [--seeds=3] [--check]   (--check: don't rewrite targets)
'use strict';
const fs = require('fs'), path = require('path');
const K = require('./kitchen');

const args = process.argv.slice(2);
const opt = (k, d) => { const a = args.find((s) => s.startsWith('--' + k)); return a ? (a.includes('=') ? a.split('=')[1] : true) : d; };
const only = args.find((a) => !a.startsWith('--'));
const SEEDS = +opt('seeds', 3), CHECK = opt('check', false);
const TARGETS = path.join(K.ROOT, 'js', 'level-targets.js');
const AXES = ['salty', 'sweet', 'sour', 'bitter', 'umami', 'rich', 'heat', 'aroma', 'body'];

const { LEVELS } = K.makeGame(1);
const levels = LEVELS.filter((l) => !only || l.id.startsWith(only));
const variant = (l, m) => K.resolve({ ...m, id: l.id + ':' + m.name, name: m.name, steps: m.steps || l.par });
const seeds = (spec) => Array.from({ length: SEEDS }, (_, s) => ({ spec, seed: s + 1 }));
const stars = (n) => '★'.repeat(n) + '☆'.repeat(3 - n);

(async () => {
  // 1. Targets from the par recipes.
  if (!CHECK) {
    const jobs = levels.flatMap((l) => seeds({ id: l.id, name: l.title, steps: l.par }));
    const res = await K.cookAll(jobs);
    const old = fs.existsSync(TARGETS) ? new Function(fs.readFileSync(TARGETS, 'utf8') + ';return LEVEL_TARGETS;')() : {};
    levels.forEach((l, n) => {
      const rs = res.slice(n * SEEDS, (n + 1) * SEEDS);
      const bad = rs.find((r) => r.error);
      if (bad) { console.log(`ERROR cooking ${l.id} par\n${bad.error}`); process.exit(1); }
      const taste = {};
      for (const ax of AXES) taste[ax] = +(rs.reduce((s, r) => s + (r.taste[ax] || 0), 0) / rs.length).toFixed(3);
      old[l.id] = { taste, type: rs[0].type };
    });
    fs.writeFileSync(TARGETS, '// Generated by tools/build-levels.js from each level\'s par recipe. Do not edit by hand.\n' +
      'const LEVEL_TARGETS = ' + JSON.stringify(old, null, 1).replace(/\n\s*/g, ' ') + ';\n');
    console.log(`Wrote targets for ${levels.length} levels to js/level-targets.js\n`);
  }

  // 2. Score par and mistakes (fresh workers load the new targets).
  const runs = [];
  for (const l of levels) {
    runs.push({ l, name: 'par', spec: { id: l.id, name: 'par', steps: l.par, level: l.id } });
    for (const m of l.mistakes || []) runs.push({ l, name: m.name, spec: { ...variant(l, m), level: l.id } });
  }
  const res = await K.cookAll(runs.flatMap((r) => seeds(r.spec)));
  let problems = 0, lastTier = -1;
  runs.forEach((run, n) => {
    const rs = res.slice(n * SEEDS, (n + 1) * SEEDS);
    const bad = rs.find((r) => r.error);
    if (bad) { console.log(`ERROR ${run.l.id} / ${run.name}\n${bad.error}`); problems++; return; }
    const L = rs.map((r) => r.level);
    const minStars = Math.min(...L.map((x) => x.stars)), maxStars = Math.max(...L.map((x) => x.stars));
    const mean = (k) => L.reduce((s, x) => s + x[k], 0) / L.length;
    const isPar = run.name === 'par';
    const ok = isPar ? minStars === 3 : maxStars < 3;
    if (!ok) problems++;
    if (isPar && run.l.tier !== lastTier) { lastTier = run.l.tier; console.log(`\n=== Tier ${run.l.tier} ===`); }
    if (isPar) console.log(`\n${run.l.title}  (teaches ${run.l.teaches})`);
    const parts = ['match', 'technique', 'ingredients', 'judges'].map((k) => `${k.slice(0, 5)} ${mean(k).toFixed(2)}`).join('  ');
    console.log(`  ${ok ? ' ' : '✗'} ${(isPar ? 'PAR' : run.name).padEnd(18)} ${stars(minStars)}${maxStars !== minStars ? '–' + maxStars : '  '}  total ${mean('total').toFixed(2)}  ${parts}  judges ${rs.map((r) => r.score.toFixed(1)).join('/')}`);
    if (!isPar || !ok) { const notes = L[0].notes.slice(0, 2); if (notes.length) console.log(`      ${notes.join(' ')}`); }
  });
  console.log(problems ? `\n${problems} problem(s): par must earn 3★ on every seed, mistakes fewer.` : '\nAll pars earn 3★ and every mistake earns fewer.');
  process.exit(problems ? 1 : 0);
})();
